# Docker Compose file for ELK stack

# Build with:
# docker-compose build elk

# Run with:
# docker-compose up

protractor:
    build: .
    container_name: protractor
    privileged: true
    shm_size: '512mb'
    restart: unless-stopped
    command: configuration_youtube.js
    volumes:
        - "protractor:/protractor/project/"