# Docker Compose file for Gremlins on docker

# Build with:
# docker-compose build gremlins-on-docker

# Run with:
# docker-compose up

gremlins-on-docker:
    build: .
    container_name: puppeteer
    privileged: true
    shm_size: '512mb'
    restart: unless-stopped
    volumes:
        - "./puppeteer/:/puppeteer/project/"